### PR TITLE
Fix incorrect function call context

### PR DESCRIPTION
**Pull request by muan**
`useNative` was introduced in #216 for patched qSA. 

Calling `document.querySelectorAll(selector, true)` causes an exception:

```
TypeError: 'querySelectorAll' called on an object that does not implement interface DocumentFragment.
```

This fails at `this.nodeType` check because `this` is the module object instead of the original call context: https://github.com/webcomponents/shadydom/blob/10f5360fb14802d53bb8f7279d6479ee03ab3f9a/src/native-methods.js#L42-L51.

### CODE REVIEW

**Comment by muan** [comment]
@TimvdLippe Added!
